# Generated by Django 6.0.3 on 2026-03-15 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_emailtemplate_event_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='event_type',
            field=models.CharField(choices=[('terms_accepted', 'Terms Accepted'), ('account_verified', 'Account Verified'), ('payment_received', 'Payment Received'), ('transaction_pending', 'Transaction Pending'), ('transaction_completed', 'Transaction Completed'), ('transaction_failed', 'Transaction Failed'), ('transaction_refunded', 'Transaction Refunded'), ('dispute_opened', 'Dispute Opened'), ('dispute_investigating', 'Dispute Investigating'), ('dispute_resolved', 'Dispute Resolved'), ('delivery_confirmed', 'Delivery Confirmed'), ('funds_released', 'Funds Released'), ('gig_created', 'Gig Created'), ('gig_accepted_client', 'Gig Accepted - Client Notification'), ('gig_accepted_hustler', 'Gig Accepted - Hustler Notification'), ('gig_started', 'Gig Started'), ('gig_pending_confirmation', 'Gig Pending Confirmation'), ('gig_completed', 'Gig Completed'), ('gig_cancelled', 'Gig Cancelled'), ('gig_disputed', 'Gig Disputed')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='historicalemailtemplate',
            name='event_type',
            field=models.CharField(choices=[('terms_accepted', 'Terms Accepted'), ('account_verified', 'Account Verified'), ('payment_received', 'Payment Received'), ('transaction_pending', 'Transaction Pending'), ('transaction_completed', 'Transaction Completed'), ('transaction_failed', 'Transaction Failed'), ('transaction_refunded', 'Transaction Refunded'), ('dispute_opened', 'Dispute Opened'), ('dispute_investigating', 'Dispute Investigating'), ('dispute_resolved', 'Dispute Resolved'), ('delivery_confirmed', 'Delivery Confirmed'), ('funds_released', 'Funds Released'), ('gig_created', 'Gig Created'), ('gig_accepted_client', 'Gig Accepted - Client Notification'), ('gig_accepted_hustler', 'Gig Accepted - Hustler Notification'), ('gig_started', 'Gig Started'), ('gig_pending_confirmation', 'Gig Pending Confirmation'), ('gig_completed', 'Gig Completed'), ('gig_cancelled', 'Gig Cancelled'), ('gig_disputed', 'Gig Disputed')], db_index=True, max_length=50),
        ),
    ]
