# Generated by Django 6.0.2 on 2026-03-11 10:14

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalTransaction',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('payment', 'Payment'), ('transfer', 'Transfer'), ('refund', 'Refund'), ('withdrawal', 'Withdrawal')], default='payment', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('awaiting_seller_acceptance', 'Awaiting Seller Acceptance'), ('awaiting_payment', 'Awaiting Payment'), ('payment_processing', 'Payment Processing'), ('funded', 'Funded'), ('in_delivery', 'In Delivery'), ('buyer_confirmed', 'Buyer Confirmed'), ('released', 'Released'), ('dispute_open', 'Dispute Open'), ('dispute_resolved_refund', 'Dispute Resolved - Refund'), ('dispute_resolved_release', 'Dispute Resolved - Release'), ('cancelled', 'Cancelled')], default='draft', max_length=40)),
                ('reference', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('merchant', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical transaction',
                'verbose_name_plural': 'historical transactions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('payment', 'Payment'), ('transfer', 'Transfer'), ('refund', 'Refund'), ('withdrawal', 'Withdrawal')], default='payment', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('awaiting_seller_acceptance', 'Awaiting Seller Acceptance'), ('awaiting_payment', 'Awaiting Payment'), ('payment_processing', 'Payment Processing'), ('funded', 'Funded'), ('in_delivery', 'In Delivery'), ('buyer_confirmed', 'Buyer Confirmed'), ('released', 'Released'), ('dispute_open', 'Dispute Open'), ('dispute_resolved_refund', 'Dispute Resolved - Refund'), ('dispute_resolved_release', 'Dispute Resolved - Release'), ('cancelled', 'Cancelled')], default='draft', max_length=40)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merchant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions_as_merchant', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions_as_buyer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
