# Generated by Django 6.0.2 on 2026-03-11 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltransaction',
            name='transaction_type',
            field=models.CharField(choices=[('payment', 'Payment'), ('transfer', 'Transfer'), ('refund', 'Refund')], default='payment', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('payment', 'Payment'), ('transfer', 'Transfer'), ('refund', 'Refund')], default='payment', max_length=20),
        ),
    ]
