# Generated by Django 6.0.3 on 2026-03-13 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disputes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dispute',
            options={},
        ),
        migrations.AlterField(
            model_name='dispute',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('under_review', 'Under Review'), ('resolved_client', 'Resolved Client'), ('resolved_hustler', 'Resolved Hustler')], default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicaldispute',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('under_review', 'Under Review'), ('resolved_client', 'Resolved Client'), ('resolved_hustler', 'Resolved Hustler')], default='open', max_length=20),
        ),
    ]
